In [9]:
import os
os.chdir(r'C:\Users\Admin\Desktop\Internship')

In [10]:
import numpy as np
import pandas as pd
data=pd.read_csv('test.csv')

In [11]:
data

angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  \
0                -0.720009              0.276801             -0.057978   
1                -0.698091              0.281343             -0.083898   
2                -0.702771              0.280083             -0.079346   
3                -0.698954              0.284114             -0.077108   
4                -0.692245              0.290722             -0.073857   
5                -0.689816              0.294896             -0.068471   
6                -0.690085              0.295282             -0.067065   
7                -0.688785              0.295981             -0.067706   
8                -0.685390              0.299394             -0.065491   
9                -0.684110              0.300822             -0.064263   
10               -0.686013              0.298478             -0.066625   
11               -0.685710              0.297687             -0.069092   
12               -0.683619              0.299401             -0.068704   
13               -0.680503              0.302289             -0.067274   
14               -0.674944              0.306351             -0.067373   
15               -0.672948              0.306460             -0.070759   
16               -0.591690              0.379258             -0.004655   
17               -0.598653              0.374095             -0.008468   
18               -0.594755              0.377131             -0.004721   
19               -0.601416              0.371978             -0.010461   
20               -0.595470              0.375913             -0.012193   
21               -0.579426              0.387695             -0.005265   
22               -0.573604              0.391731             -0.005176   
23               -0.587638              0.379843             -0.023736   
24               -0.601530              0.368305             -0.034342   
25               -0.604059              0.367321             -0.030170   
26               -0.600177              0.371195             -0.023182   
27               -0.596625              0.374298             -0.018806   
28               -0.597761              0.373296             -0.020333   
29               -0.598912              0.372410             -0.020935   
...                    ...                   ...                   ...   
2917             -0.694649              0.245906              0.172715   
2918             -0.722767              0.244779              0.144695   
2919             -0.694613              0.259140              0.157683   
2920             -0.671194              0.265751              0.174766   
2921             -0.661045              0.270618              0.179726   
2922             -0.657085              0.276184              0.177337   
2923             -0.663506              0.273305              0.173953   
2924             -0.660163              0.274327              0.176291   
2925             -0.652636              0.277868              0.180047   
2926             -0.656760              0.271648              0.182987   
2927             -0.657011              0.266990              0.187901   
2928             -0.807271              0.189885              0.118456   
2929             -0.814760              0.190418              0.110325   
2930             -0.809277              0.192232              0.113997   
2931             -0.809257              0.185954              0.120358   
2932             -0.800932              0.190968              0.123600   
2933             -0.803888              0.191732              0.119944   
2934             -0.810091              0.184712              0.120724   
2935             -0.797719              0.194819              0.122937   
2936             -0.803914              0.196823              0.114498   
2937             -0.691122              0.241953              0.180141   
2938             -0.677946              0.256877              0.177768   
2939      

In [18]:
data['Activity'].replace(['LAYING','STANDING','WALKING','SITTING','WALKING_UPSTAIRS','WALKING_DOWNSTAIRS'],['0','1','00','11','000','111'],inplace=True)

In [19]:
x=data.iloc[:,0:3]
y=data.iloc[:,3]

In [20]:
x

angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)
0                -0.720009              0.276801             -0.057978
1                -0.698091              0.281343             -0.083898
2                -0.702771              0.280083             -0.079346
3                -0.698954              0.284114             -0.077108
4                -0.692245              0.290722             -0.073857
5                -0.689816              0.294896             -0.068471
6                -0.690085              0.295282             -0.067065
7                -0.688785              0.295981             -0.067706
8                -0.685390              0.299394             -0.065491
9                -0.684110              0.300822             -0.064263
10               -0.686013              0.298478             -0.066625
11               -0.685710              0.297687             -0.069092
12               -0.683619              0.299401             -0.068704
13               -0.680503              0.302289             -0.067274
14               -0.674944              0.306351             -0.067373
15               -0.672948              0.306460             -0.070759
16               -0.591690              0.379258             -0.004655
17               -0.598653              0.374095             -0.008468
18               -0.594755              0.377131             -0.004721
19               -0.601416              0.371978             -0.010461
20               -0.595470              0.375913             -0.012193
21               -0.579426              0.387695             -0.005265
22               -0.573604              0.391731             -0.005176
23               -0.587638              0.379843             -0.023736
24               -0.601530              0.368305             -0.034342
25               -0.604059              0.367321             -0.030170
26               -0.600177              0.371195             -0.023182
27               -0.596625              0.374298             -0.018806
28               -0.597761              0.373296             -0.020333
29               -0.598912              0.372410             -0.020935
...                    ...                   ...                   ...
2917             -0.694649              0.245906              0.172715
2918             -0.722767              0.244779              0.144695
2919             -0.694613              0.259140              0.157683
2920             -0.671194              0.265751              0.174766
2921             -0.661045              0.270618              0.179726
2922             -0.657085              0.276184              0.177337
2923             -0.663506              0.273305              0.173953
2924             -0.660163              0.274327              0.176291
2925             -0.652636              0.277868              0.180047
2926             -0.656760              0.271648              0.182987
2927             -0.657011              0.266990              0.187901
2928             -0.807271              0.189885              0.118456
2929             -0.814760              0.190418              0.110325
2930             -0.809277              0.192232              0.113997
2931             -0.809257              0.185954              0.120358
2932             -0.800932              0.190968              0.123600
2933             -0.803888              0.191732              0.119944
2934             -0.810091              0.184712              0.120724
2935             -0.797719              0.194819              0.122937
2936             -0.803914              0.196823              0.114498
2937             -0.691122              0.241953              0.180141
2938             -0.677946              0.256877              0.177768
2939             -0.672635              0.261034              0.178609
2940             -0.660366              0.272243              0.178547
2941             -0.646754    

In [21]:
y

0         1
1         1
2         1
3         1
4         1
5         1
6         1
7         1
8         1
9         1
10        1
11        1
12        1
13        1
14        1
15        1
16        1
17        1
18        1
19        1
20        1
21        1
22        1
23        1
24        1
25        1
26        1
27        1
28        1
29        1
       ... 
2917    000
2918    000
2919    000
2920    000
2921    000
2922    000
2923    000
2924    000
2925    000
2926    000
2927    000
2928    111
2929    111
2930    111
2931    111
2932    111
2933    111
2934    111
2935    111
2936    111
2937    000
2938    000
2939    000
2940    000
2941    000
2942    000
2943    000
2944    000
2945    000
2946    000
Name: Activity, Length: 2947, dtype: object

In [22]:
from sklearn.model_selection import cross_validate,train_test_split,cross_val_score,cross_val_predict
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [23]:
y1_train=y_train.astype('int')
y1_train

441       0
692       0
2510      0
1028    111
2364    111
1601      0
1091     11
1147      0
2316      0
1788      0
682       0
1557     11
345      11
216       0
853       0
2737      0
1844      0
1398     11
2388      0
1828      0
273     111
418     111
577     111
1203      1
1474      0
2633      0
1764      0
2129      0
2454     11
2035      0
       ... 
2563      0
972       0
1391      1
2647      0
2878      0
2443     11
253       0
1799      0
2272     11
1026    111
1025    111
2649      0
2420      1
161       1
956       0
1933      0
171       1
1726     11
2201      0
2572      1
1142      0
2587      1
2456     11
2054      1
1464      0
1501      0
514      11
2166    111
1387      1
1717      1
Name: Activity, Length: 2357, dtype: int32

In [24]:
from sklearn import preprocessing
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0.14536648, 0.62209457, 0.46362736],
       [0.15742698, 0.62446791, 0.45014396],
       [0.15485148, 0.62380956, 0.45251181],
       ...,
       [0.1809411 , 0.62088108, 0.58803909],
       [0.17854107, 0.61581385, 0.59135763],
       [0.17834208, 0.61537208, 0.59163879]])

In [26]:
x_train_std=minmax.fit_transform(x_train)
x_test_std=minmax.fit_transform(x_test)
x_train_std

array([[0.1237867 , 0.61137702, 0.47386454],
       [0.02979988, 0.55426199, 0.49862067],
       [0.1858109 , 0.65599688, 0.48882719],
       ...,
       [0.15134254, 0.60194635, 0.58097043],
       [0.13437096, 0.62309199, 0.50160941],
       [0.14008754, 0.6260448 , 0.49035112]])

In [33]:
from sklearn import neighbors
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [35]:
y_pred=clf.predict(x_test)

In [36]:
y_test=y_test.astype('int')
y_test

1784      0
2211    111
1345      0
1881      1
709       0
2486      0
479       1
2203    111
1703      1
329       1
106       0
2018    111
1204      1
1354      0
1768      0
2487      0
640       1
2360    111
1723     11
2466      0
2836      0
1896     11
592     111
265     111
1761      0
2807     11
2419      1
2284     11
884       0
1865      1
       ... 
467       1
144       0
610       0
664      11
2165    111
667       0
2794     11
2497      0
1211      1
1656    111
1725     11
2637      0
2804     11
779       1
2852      0
117     111
2699    111
1481    111
747     111
2724      0
324       1
930      11
1819    111
2547      0
2558      0
2401      1
2004    111
1042      0
2528    111
307       1
Name: Activity, Length: 590, dtype: int32

In [37]:
y_pred=y_pred.astype('int')
y_pred

array([  0, 111,   1,   1,   0,   0,   1,   0,   1,   1,   0,   1,   1,
         0,   0,   0, 111, 111,  11,   0,   0,  11, 111, 111,   0,  11,
         1,  11,   0,   1,   1, 111,   0,  11,   0,   0,   0, 111,   0,
         1,   0,   0,   0,  11,   1,   0,   1,   0,  11,   1,   0,  11,
         0,   0,  11,  11,   0,  11,   1,   0,   0,   0,   1,   0,  11,
         1,  11,   1,  11,  11,  11,   0,   0,   1,   0,   0,   0,   1,
         1,   0, 111,  11,   0,   1,  11,   0,   1,   0,   0,  11,   0,
         0,  11, 111,   0,   0,   0,   0,  11,   1,   0,   0,  11,   0,
         1,   0,   0,  11,   0,   0,   0,  11,   1,  11,   0,   0,   1,
         0,   0,   0,   0,   0,   1,   0,   0,   0,   0,   1,   0,   0,
         0,   0,  11,   0,   1,   0, 111,   0, 111,   0, 111,   1,  11,
         0,   1,   1,   1,   0,   0,   0,   0,   1,   1,   0,   1,   0,
         0,   0,   0,  11,   0,  11,  11,   1,  11,   1, 111,   0,   1,
         0,   0,   0,   1,   0,   0,  11,  11,   0,   1, 111,  1

In [39]:
print("Accuracy Score : %f"%(accuracy_score(y_test,y_pred)*100))

Accuracy Score : 83.559322


In [ ]:
import socket, traceback, string
from sys import stderr
host = ''
port = 5555
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
s.bind((host, port))
while 1:
    try:
        message, address = s.recvfrom(8192)
        print(message.decode())
        print("\n\n\n\n\n")
        message=message.decode()
        data = message.split( "," )
        t = data[0]
        sensorID = int(data[1])
        if sensorID==3:     
            ax, ay, az = data[2], data[3], data[4]
    except (KeyboardInterrupt, SystemExit):
        raise
    except:
        traceback.print_exc()
while 1:
    data,addr=s.recvfrom(8192)
    data=data.decode()
    data=data.split(",")
    print(data)

In [ ]:
sensorID = int(data[1])
    if sensorID==3:     
        ax, ay, az = data[2], data[3], data[4]
ypred=clf.predict([[ax,ay,az]])
ypred